services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3606:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    links: 
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres2
    restart: always
    environment:
      POSTGRES_NAME: postgres2
      POSTGRES_USER: exemplo
      POSTGRES_PASSWORD: exemplo
    ports:
      - "3605:5432"
    
#docker compose up -d  docker compose stop e docker compose down

